module.exports = {
  LOAD_START: 'account/LOAD_START',
  LOAD_END: 'account/LOAD_END',
  LOAD_ERROR: 'account/LOAD_ERROR',
  GET_BUSINESS_ACCOUNTS: 'account/GET_BUSINESS_ACCOUNTS',
  UPDATE_SELECTED_BUSINESS_ACCOUNT: 'account/UPDATE_SELECTED_BUSINESS_ACCOUNT',
  UPDATE_WALLET_ALLOCATION: 'account/UPDATE_WALLET_ALLOCATION',
  GET_INFLOW_OUTFLOW: 'account/GET_INFLOW_OUTFLOW',
  GET_WALLET_INFLOW_OUTFLOW: 'account/GET_WALLET_INFLOW_OUTFLOW',
  GET_WALLET_TRANSACTIONS: 'account/GET_WALLET_TRANSACTIONS',
  GET_STATEMENTS: 'account/GET_STATEMENTS',
  CHANGE_PLAN: 'account/CHANGE_PLAN',
};
