module.exports = {
  UPDATE_USER_STATS: 'app/UPDATE_USER_STATS',
  LOAD_PROFILE_REQUEST: 'app/LOAD_PROFILE_REQUEST',
  LOAD_PROFILE_RECIEVED: 'app/LOAD_PROFILE_RECIEVED',
  LOAD_ERROR: 'app/LOAD_ERROR',
  CLEAR_ERROR: 'app/CLEAR_ERROR',
  LOAD_START: 'app/LOAD_START',
  LOAD_END: 'app/LOAD_END',
  LOAD_BUSINESS_ACCOUNTS_REQUEST: 'app/LOAD_BUSINESS_ACCOUNTS_REQUEST',
  LOAD_BUSINESS_ACCOUNTS_RECEIVED: 'app/LOAD_BUSINESS_ACCOUNTS_RECEIVED',
  UPDATE_SELECTED_BUSINESS_ACCOUNT: 'app/UPDATE_SELECTED_BUSINESS_ACCOUNT',
  LOAD_ADMIN_ACCOUNT_RECEIVED: 'app/LOAD_ADMIN_ACCOUNT_RECEIVED',
  LOAD_ADMIN_ACCOUNT_REQUEST: 'app/LOAD_ADMIN_ACCOUNT_REQUEST',
};
