module.exports = {
  UPDATE_SAMPLE_REQUEST: 'sample/UPDATE_SAMPLE_REQUEST',
  LOAD_SAMPLE_REQUEST: 'sample/LOAD_SAMPLE_REQUEST',
  LOAD_SAMPLE_RECEIVED: 'sample/LOAD_SAMPLE_RECEIVED',
  LOAD_ERROR: 'sample/LOAD_ERROR',
  CLEAR_ERROR: 'sample/CLEAR_ERROR',
  LOAD_START: 'sample/LOAD_START',
  LOAD_END: 'sample/LOAD_END',
};
