module.exports = {
  LOAD_TRANSACTION_REQUEST: 'transaction/LOAD_TRANSACTION_REQUEST',
  LOAD_TRANSACTION_RECEIVED: 'transaction/LOAD_TRANSACTION_RECEIVED',
  LOAD_ERROR: 'transaction/LOAD_ERROR',
  CLEAR_ERROR: 'transaction/CLEAR_ERROR',
  LOAD_START: 'transaction/LOAD_START',
  LOAD_END: 'transaction/LOAD_END',
};
