module.exports = {
  LOAD_TRANSFER_RECEIVED: 'transfers/LOAD_TRANSFER_RECEIVED',
  LOAD_BENEFICIARY_RECEIVED: 'transfers/LOAD_BENEFICIARY_RECEIVED',
  LOAD_LISTED_BANKS_RECEIVED: 'transfers/LOAD_LISTED_BANKS_RECEIVED',
  LOAD_FIRST_STEP_RECEIVED: 'transfers/LOAD_FIRST_STEP_RECEIVED',
  LOAD_TRANSFER_TO_NUMBER: 'transfers/LOAD_TRANSFER_TO_NUMBER',
  LOAD_PENDING_RECEIVED: 'transfers/LOAD_PENDING_RECEIVED',
  LOAD_START: 'transfers/LOAD_START',
  LOAD_END: 'transfers/LOAD_END',
};
